production:
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV['DB_POOL'] || ENV['RAILS_MAX_THREADS'] || 5 %>
  reaping_frequency: <%= ENV['DB_REAP_FREQ'] || 10 %>

development:
  adapter: postgresql
  database: video_list_exercise_development
  host: localhost

test:
  adapter: postgresql
  database: video_list_exercise_test
  host: localhost
  pool: 5
